version: '3.1'
services:
  db:
    image: mysql
    container_name: pixkeydb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - pixkey:/var/lib/mysql

volumes:
  pixkey: